name: webview_linux
description: "A lightweight Dart FFI binding package for embedding WebKitGTK 4.1 webview into Linux applications.
version: 0.0.1
repository: https://github.com/ThanCoder/webview_linux.git

environment:
  sdk: ^3.12.0

dependencies:
  code_assets: ^1.2.1
  hooks: ^2.0.2
  ffi: ^2.2.0

dev_dependencies:
  ffigen: ^20.1.1
  flutter_lints: ^6.0.0
  test: ^1.28.0
