// AUTO GENERATED FILE, DO NOT EDIT.
//
// Generated by `package:ffigen`.
// ignore_for_file: type=lint, unused_import
import 'dart:ffi' as ffi;

/// Creates a new webview instance. If debug is non-zero - developer tools will
/// be enabled (if the platform supports them). Window parameter can be a
/// pointer to the native window handle. If it's non-null - then child WebView
/// is embedded into the given parent window. Otherwise a new window is created.
/// Depending on the platform, a GtkWindow, NSWindow or HWND pointer can be
/// passed here.
@ffi.Native<webview_t Function(ffi.Int, ffi.Pointer<ffi.Void>)>()
external webview_t webview_create(int debug, ffi.Pointer<ffi.Void> window);

/// Destroys a webview and closes the native window.
@ffi.Native<ffi.Void Function(webview_t)>()
external void webview_destroy(webview_t w);

/// Runs the main loop until it's terminated. After this function exits - you
/// must destroy the webview.
@ffi.Native<ffi.Void Function(webview_t)>()
external void webview_run(webview_t w);

/// Stops the main loop. It is safe to call this function from another other
/// background thread.
@ffi.Native<ffi.Void Function(webview_t)>()
external void webview_terminate(webview_t w);

/// Posts a function to be executed on the main thread. You normally do not need
/// to call this function, unless you want to tweak the native window.
@ffi.Native<
  ffi.Void Function(
    webview_t,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(webview_t w, ffi.Pointer<ffi.Void> arg)
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void webview_dispatch(
  webview_t w,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(webview_t w, ffi.Pointer<ffi.Void> arg)
    >
  >
  fn,
  ffi.Pointer<ffi.Void> arg,
);

/// Returns a native window handle pointer. When using GTK backend the pointer
/// is GtkWindow pointer, when using Cocoa backend the pointer is NSWindow
/// pointer, when using Win32 backend the pointer is HWND pointer.
@ffi.Native<ffi.Pointer<ffi.Void> Function(webview_t)>()
external ffi.Pointer<ffi.Void> webview_get_window(webview_t w);

/// Updates the title of the native window. Must be called from the UI thread.
@ffi.Native<ffi.Void Function(webview_t, ffi.Pointer<ffi.Char>)>()
external void webview_set_title(webview_t w, ffi.Pointer<ffi.Char> title);

/// Updates native window size. See WEBVIEW_HINT constants.
@ffi.Native<ffi.Void Function(webview_t, ffi.Int, ffi.Int, ffi.Int)>()
external void webview_set_size(webview_t w, int width, int height, int hints);

/// Navigates webview to the given URL. URL may be a data URI, i.e.
/// "data:text/text,<html>...</html>". It is often ok not to url-encode it
/// properly, webview will re-encode it for you.
@ffi.Native<ffi.Void Function(webview_t, ffi.Pointer<ffi.Char>)>()
external void webview_navigate(webview_t w, ffi.Pointer<ffi.Char> url);

/// Injects JavaScript code at the initialization of the new page. Every time
/// the webview will open a the new page - this initialization code will be
/// executed. It is guaranteed that code is executed before window.onload.
@ffi.Native<ffi.Void Function(webview_t, ffi.Pointer<ffi.Char>)>()
external void webview_init(webview_t w, ffi.Pointer<ffi.Char> js);

/// Evaluates arbitrary JavaScript code. Evaluation happens asynchronously, also
/// the result of the expression is ignored. Use RPC bindings if you want to
/// receive notifications about the results of the evaluation.
@ffi.Native<ffi.Void Function(webview_t, ffi.Pointer<ffi.Char>)>()
external void webview_eval(webview_t w, ffi.Pointer<ffi.Char> js);

/// Binds a native C callback so that it will appear under the given name as a
/// global JavaScript function. Internally it uses webview_init(). Callback
/// receives a request string and a user-provided argument pointer. Request
/// string is a JSON array of all the arguments passed to the JavaScript
/// function.
@ffi.Native<
  ffi.Void Function(
    webview_t,
    ffi.Pointer<ffi.Char>,
    ffi.Pointer<
      ffi.NativeFunction<
        ffi.Void Function(
          ffi.Pointer<ffi.Char> seq,
          ffi.Pointer<ffi.Char> req,
          ffi.Pointer<ffi.Void> arg,
        )
      >
    >,
    ffi.Pointer<ffi.Void>,
  )
>()
external void webview_bind(
  webview_t w,
  ffi.Pointer<ffi.Char> name,
  ffi.Pointer<
    ffi.NativeFunction<
      ffi.Void Function(
        ffi.Pointer<ffi.Char> seq,
        ffi.Pointer<ffi.Char> req,
        ffi.Pointer<ffi.Void> arg,
      )
    >
  >
  fn,
  ffi.Pointer<ffi.Void> arg,
);

/// Allows to return a value from the native binding. Original request pointer
/// must be provided to help internal RPC engine match requests with responses.
/// If status is zero - result is expected to be a valid JSON result value.
/// If status is not zero - result is an error JSON object.
@ffi.Native<
  ffi.Void Function(
    webview_t,
    ffi.Pointer<ffi.Char>,
    ffi.Int,
    ffi.Pointer<ffi.Char>,
  )
>()
external void webview_return(
  webview_t w,
  ffi.Pointer<ffi.Char> seq,
  int status,
  ffi.Pointer<ffi.Char> result,
);

@ffi.Native<ffi.Int>()
external int webview;

typedef webview_t = ffi.Pointer<ffi.Void>;

const int WEBVIEW_HINT_NONE = 0;

const int WEBVIEW_HINT_MIN = 1;

const int WEBVIEW_HINT_MAX = 2;

const int WEBVIEW_HINT_FIXED = 3;
